# Project information
site_name: LT会ポータル
site_description: 'LT会の色々'
site_author: 'kit_systemyou'
site_url: 'https://kitsystemyou.github.io/LT_Portal/'

# Copyright
copyright: 'Copyright (c) 2021'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  palette:
    primary: 'Blue'
    accent: 'Orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'github-user-name'
    twitter: 'twitter-author'

# Extensions
markdown_extensions:
  - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true
  - admonition
# - toc:
#   permalink: '#'