# Project information
site_name: LTä¼šãƒãƒ¼ã‚¿ãƒ«
site_description: 'LTä¼šã®è‰²ã€…'
site_author: 'kit_systemyou'
site_url: 'https://kitsystemyou.github.io/LT_Portal/'

# Copyright
copyright: 'Copyright (c) 2021'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Options
extra:
  palette:
    primary: 'Blue'
    accent: 'Orange'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  i18n:
    prev: 'Previous'
    next: 'Next'
  author:
    github: 'github-user-name'
    twitter: 'twitter-author'

# Extensions
markdown_extensions:
  - codehilite:
        noclasses: true
        pygments_style: colorful
        linenums: true
  - admonition
  - fontawesome_markdown

extra_css:
  - "https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css"

# pages
pages:
  - ã‚ˆã†ã“ã âœ¨: 'index.md'
  - ä»Šå¾Œã®ã‚¹ã‚±ã‚¸ãƒ¥ãƒ¼ãƒ«: 'schedules.md'
  - ãƒãƒƒã‚¯ãƒŠãƒ³ãƒãƒ¼:
    - ç¬¬1å› LTä¼š: 'backnumber/ltmeeting1.md'
    - ç¬¬2å› LTä¼š: 'backnumber/ltmeeting2.md'
    - ç¬¬3å› LTä¼š: 'backnumber/ltmeeting3.md'
    - ç¬¬4å› LTä¼š: 'backnumber/ltmeeting4.md'
    - ç¬¬5å› LTä¼š: 'backnumber/ltmeeting5.md'
    - ç¬¬6å› LTä¼š: 'backnumber/ltmeeting6.md'
  - Theme ğŸ“¢: 'theme.md'
  - ãƒšãƒ¼ã‚¸ã®ç·¨é›†ğŸ¨: 'editpage.md'