# master ブランチに push されたときに実行される

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      # Pipenv でパッケージ管理している場合を想定しています。
      - run: python -m pip install pipenv
      # Pipfile.lock を Git 管理に含めている場合を想定しています。
      - run: python -m pipenv sync --dev
      # まず、ビルドします。
      - run: python -m pipenv run mkdocs build
      - uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          # publish_branch を指定しない場合、
          # gh-pages ブランチにデプロイされます。
          publish_branch: master
          publish_dir: ./site
